name: Trigger auto deployment for container-app-22wmza2eahlky

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-22wmza2eahlky-AutoDeployTrigger-5fc91000-90be-4418-9402-997dcb93cfe4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP22WMZA2EAHLKY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP22WMZA2EAHLKY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP22WMZA2EAHLKY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP22WMZA2EAHLKY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP22WMZA2EAHLKY_REGISTRY_PASSWORD }}
          containerAppName: container-app-22wmza2eahlky
          resourceGroup: myragappspace8816
          imageToBuild: default/container-app-22wmza2eahlky:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


